//Listar todos os usuários
GET http://localhost:5000/teste-esqueleton-backend/us-central1/aplication/user

###
//Listar um usuário específico
GET http://localhost:5000/teste-esqueleton-backend/us-central1/aplication/user/48fda34c-6a17-48ba-abe5-d1738e9f79de

###
//Criar um usuario
POST http://localhost:5000/teste-esqueleton-backend/us-central1/aplication/user/
Content-Type: application/json

{
  "name": "Planta Teste",
  "lastName": "da planta teste",
  "birthdate": "02/04/1992",
  "cpf": "405.967.938-04",
  "email": "gabriel@gmail.com",
  "address": {
      "street": "rua teste",
      "complement": "apto 1",
      "numberHome": "123",
      "district": "bairro teste",
      "state": "sp",
      "city": "são paulo",
      "country": "brasil"
    },
    "typeUser": "User"
}

###
//Atualizar um usuário
PUT http://localhost:5000/teste-esqueleton-backend/us-central1/aplication/user/48fda34c-6a17-48ba-abe5-d1738e9f79de
Content-Type: application/json

{
  "name": "Planta Teste3",
  "lastName": "da planta teste4"
}

###
//Deletar um usuário
DELETE http://localhost:5000/teste-esqueleton-backend/us-central1/aplication/user/48fda34c-6a17-48ba-abe5-d1738e9f79de


    
