//Listar todas as plantas
GET http://localhost:5000/teste-esqueleton-backend/us-central1/cannabisApp/plant

###
//Listar uma planta específica
GET http://localhost:5000/teste-esqueleton-backend/us-central1/cannabisApp/plant/1db80f7a-cbd5-4d79-9ee2-5de2c2368786

###
//Criar uma planta
POST http://localhost:5000/teste-esqueleton-backend/us-central1/cannabisApp/plant
Content-Type: application/json

{
  "scientificName": "Planta Teste",
  "popularName": "da planta teste",
  "species": "Sativa",
  "image": "link da imagem"
}

###
//Deletar uma planta
DELETE http://localhost:5000/teste-esqueleton-backend/us-central1/cannabisApp/plant/83a2b0ad-fe40-43bb-8d77-24d97ea7d292

###
//Atualizar uma planta
PUT http://localhost:5000/teste-esqueleton-backend/us-central1/cannabisApp/plant/1db80f7a-cbd5-4d79-9ee2-5de2c2368786
Content-Type: application/json

{
  "scientificName": "Planta Teste update 2",
  "popularName": "da planta teste update 2"
}